# Generated by Django 5.0.1 on 2024-05-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('PaperID', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('PublisherName', models.CharField(blank=True, max_length=512, null=True)),
                ('PublisherID', models.CharField(blank=True, max_length=512, null=True)),
                ('DOI', models.CharField(max_length=255, unique=True)),
                ('Title', models.CharField(blank=True, max_length=512, null=True)),
                ('JournalName', models.CharField(blank=True, max_length=512, null=True)),
                ('ScopusIndexed', models.BooleanField(default=True)),
                ('WOSIndexed', models.BooleanField(blank=True, null=True)),
                ('ScopusQuartile', models.CharField(blank=True, max_length=10, null=True)),
                ('WOSImpactFactors', models.CharField(blank=True, max_length=512, null=True)),
                ('VolumeNumber', models.IntegerField(blank=True, null=True)),
                ('IssueNumber', models.IntegerField(blank=True, null=True)),
                ('PageNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('DateOfPublication', models.DateField(blank=True, null=True)),
                ('CitationCount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
